<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>cv.sh - Interactive Resume</title>
  <link rel="stylesheet" href="https://daffi1238.github.io/cv.sh/style.css">
</head>
<body>
  <div class="terminal" id="terminal">
    <!-- Terminal content will be dynamically generated by JavaScript -->
  </div>

  <script src="https://daffi1238.github.io/cv.sh/script.js"></script>
</body>
</html> 