### Site Settings ###
title               : HackeMate
description         : >-
                      I turn coffee :coffee: into code,
                      use tabs over spaces
                      and never broke production.
baseurl             : "/portfolYOU"            # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : yousinix/portfolYOU      # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : yousinix/portfolYOU
open_new_tab        : false                    # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**                           # For Documentation Only


### Author Info ###
author:
  name              : daffi1238
  image             : https://i.imgur.com/uyDNQnn.jpg
  behance           : daffi1238
# dribbble          : daffi1238
  email             : username@domain.com
  facebook          : daffi1238
  github            : daffi1238
# gitlab            : daffi1238
# instagram         : daffi1238
# kaggle            : daffi1238
  linkedin          : daffi1238
  medium            : daffi1238
# soundcloud        : daffi1238
# spotify           : daffi1238
# stackoverflow     : your_user_id
# tumblr            : daffi1238.tumblr.com
# twitch            : daffi1238
  twitter           : daffi1238
# vimeo             : daffi1238
# youtube           : your_channel_name
# keybase           : daffi1238


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:                                             # For Documentation Only
    output: true                                        # For Documentation Only
  ctfs:                                                 # Nueva colección añadida
    output: true                                        # Activa la generación de páginas HTML
    permalink: /ctfs/:name                              # Define la estructura del enlace


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: daffi1238
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:                                              # For Documentation Only
      path: ""                                          # For Documentation Only
      type: "elements"                                  # For Documentation Only
    values:                                             # For Documentation Only
      layout: "element"                                 # For Documentation Only
  - scope:                                              # Para elementos de la colección "elements"
      path: "" 
      type: "elements"
    values:
      layout: "ctfs"                                    # Esto puede cambiarse si necesitas otro layout
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments
  - scope:                                              # Configuración para la nueva colección "ctfs"
      path: ""
      type: "ctfs"
    values:
      layout: "ctf"                                     # Layout específico para "ctfs"


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
